---
- name: Restart postgresql
  environment:
    XDG_RUNTIME_DIR: "{{ foremanctl_xdg_runtime_dir }}"
  become: true
  become_user: "{{ foremanctl_user }}"
  ansible.builtin.systemd:
    name: "{{ postgresql_container_name }}"
    state: restarted
    scope: user
