---
postgresql_container_image: quay.io/sclorg/postgresql-13-c9s
postgresql_container_tag: "latest"
postgresql_container_name: postgresql
postgresql_network: host
postgresql_restart_policy: always

postgresql_data_dir: /var/lib/pgsql/data

postgresql_admin_password: "CHANGEME"

postgresql_max_connections: 500
postgresql_shared_buffers: 512MB
