---
iop_vulnerability_frontend_container_image: "quay.io/iop/vulnerability-frontend"
iop_vulnerability_frontend_container_tag: "foreman-3.16"
iop_vulnerability_frontend_assets_path: "/var/lib/foreman/public/assets/apps/vulnerability"
iop_vulnerability_frontend_source_path: "/srv/dist/."
