---
hammer_foreman_server_url: "https://{{ ansible_facts['fqdn'] }}"
hammer_ca_certificate: ""
hammer_default_plugins:
  - foreman
hammer_plugins: []
hammer_packages: "{{ (hammer_default_plugins+hammer_plugins) | map('regex_replace', '^', 'hammer-cli-plugin-') }}"
