---
help: |
  Generate a certificate bundle

variables:
  hostname:
    parameter: hostname
    help: Hostname to generate a certificate bundle for that will be the common name.

include:
  - _certificate_source
