---
iop_remediation_container_image: "quay.io/iop/remediations"
iop_remediation_container_tag: "foreman-3.16"

iop_remediation_database_name: remediations_db
iop_remediation_database_user: remediations_user
iop_remediation_database_password: CHANGEME
iop_remediation_database_host: "localhost"
iop_remediation_database_port: "5432"
