---
- name: Extract the DN from the client certificate
  ansible.builtin.command: "openssl x509 -in {{ candlepin_client_certificate }} -noout -subject -nameopt rfc2253,sep_comma_plus_space"
  changed_when: false
  register: candlepin_openssl_response

- name: Set candlepin_artemis_client_dn
  ansible.builtin.set_fact:
    candlepin_artemis_client_dn: "{{ candlepin_openssl_response.stdout | replace('subject=', '') }}"

- name: Configure Artemis secrets as rootless user
  environment:
    XDG_RUNTIME_DIR: "{{ foremanctl_xdg_runtime_dir }}"
  become: true
  become_user: "{{ foremanctl_user }}"
  block:
    - name: Create Candlepin broker.xml
      containers.podman.podman_secret:
        state: present
        name: candlepin-artemis-broker-xml
        data: "{{ lookup('ansible.builtin.template', 'broker.xml.j2') }}"
        labels:
          filename: broker.xml
          app: artemis
      notify:
        - Restart candlepin

    - name: Create Tomcat login config
      containers.podman.podman_secret:
        state: present
        name: candlepin-artemis-login-config
        data: "{{ lookup('ansible.builtin.template', 'login.config') }}"
        labels:
          filename: login.config
          app: artemis
      notify:
        - Restart candlepin

    - name: Create Tomcat jaas.conf
      containers.podman.podman_secret:
        state: present
        name: candlepin-artemis-jaas-conf
        data: "{{ lookup('ansible.builtin.template', 'jaas.conf') }}"
        labels:
          filename: jaas.conf
          app: artemis
      notify:
        - Restart candlepin

    - name: Create Tomcat cert-roles.properties
      containers.podman.podman_secret:
        state: present
        name: candlepin-artemis-cert-roles-properties
        data: "{{ lookup('ansible.builtin.template', 'cert-roles.properties') }}"
        labels:
          filename: cert-roles.properties
          app: artemis
      notify:
        - Restart candlepin

    - name: Create Tomcat cert-users.properties
      containers.podman.podman_secret:
        state: present
        name: candlepin-artemis-cert-users-properties
        data: "{{ lookup('ansible.builtin.template', 'cert-users.properties.j2') }}"
        labels:
          filename: cert-users.properties
          app: artemis
      notify:
        - Restart candlepin
