---
- name: Set up Foreman Proxy
  hosts:
    - quadlet
  become: true
  vars_files:
    - "../../vars/defaults.yml"
    - "../../vars/{{ certificate_source }}_certificates.yml"
    - "../../vars/foreman.yml"
    - "../../vars/images.yml"
  vars:
    foreman_url: "https://{{ ansible_facts['fqdn'] }}"

  roles:
    - pre_install
    - checks
    - foreman_proxy
