---
- name: Extract the DN from the client certificate
  ansible.builtin.command: "openssl x509 -in {{ candlepin_client_certificate }} -noout -subject -nameopt rfc2253,sep_comma_plus_space"
  changed_when: false
  register: openssl_response

- name: Set candlepin_artemis_client_dn
  ansible.builtin.set_fact:
    candlepin_artemis_client_dn: "{{ openssl_response.stdout | replace('subject=', '') }}"

- name: Create Candlepin keystore password secret
  containers.podman.podman_secret:
    state: present
    name: candlepin-keystore-password
    data: "{{ candlepin_keystore_password }}"

- name: Create Tomcat login config
  containers.podman.podman_secret:
    state: present
    name: candlepin-artemis-login-config
    data: "{{ lookup('ansible.builtin.template', 'login.config') }}"
    labels:
      filename: login.config
      app: artemis

- name: Create Tomcat jaas.conf
  containers.podman.podman_secret:
    state: present
    name: candlepin-artemis-jaas-conf
    data: "{{ lookup('ansible.builtin.template', 'jaas.conf') }}"
    labels:
      filename: jaas.conf
      app: artemis

- name: Create Tomcat cert-roles.properties
  containers.podman.podman_secret:
    state: present
    name: candlepin-artemis-cert-roles-properties
    data: "{{ lookup('ansible.builtin.template', 'cert-roles.properties') }}"
    labels:
      filename: cert-roles.properties
      app: artemis

- name: Create Tomcat cert-users.properties
  containers.podman.podman_secret:
    state: present
    name: candlepin-artemis-cert-users-properties
    data: "{{ lookup('ansible.builtin.template', 'cert-users.properties.j2') }}"
    labels:
      filename: cert-users.properties
      app: artemis
