---
iop_vulnerability_container_image: "quay.io/iop/vulnerability-engine"
iop_vulnerability_container_tag: "foreman-3.16"

iop_vulnerability_database_name: vulnerability_db
iop_vulnerability_database_user: vulnerability_admin
iop_vulnerability_database_password: CHANGEME
iop_vulnerability_database_host: "host.containers.internal"
iop_vulnerability_database_port: "5432"

# Taskomatic configuration
iop_vulnerability_taskomatic_jobs: "stale_systems:5,delete_systems:30,cacheman:5"
iop_vulnerability_taskomatic_startup: "cacheman"
