---
variables:
  tuning:
    help: Tuning profile to apply. Defaults to default. Set to a different value according to the available hardware.
    choices:
      - default
      - medium
      - large
      - extra-large
      - extra-extra-large
      - development
