---
- name: Setup quadlet demo machine
  hosts: all
  become: true
  vars:
    certificates_hostnames:
      - localhost
    candlepin_db_password: "CHANGEME"
    candlepin_keystore_password: "CHANGEME"
    candlepin_oauth_secret: "CHANGEME"
    candlepin_ca_key: "{{ certificates_ca_directory }}/private/ca.key"
    candlepin_ca_certificate: "{{ certificates_ca_directory }}/certs/ca.crt"
    candlepin_tomcat_key: "{{ certificates_ca_directory }}/private/localhost.key"
    candlepin_tomcat_certificate: "{{ certificates_ca_directory }}/certs/localhost.crt"
    candlepin_client_key: "{{ certificates_ca_directory }}/private/{{ certificates_server }}-client.key"
    candlepin_client_certificate: "{{ certificates_ca_directory }}/certs/{{ certificates_server }}-client.crt"
    foreman_proxy_ca_certificate: "{{ certificates_ca_directory }}/certs/ca.crt"
    foreman_proxy_server_key: "{{ certificates_ca_directory }}/private/{{ certificates_server }}.key"
    foreman_proxy_server_certificate: "{{ certificates_ca_directory }}/certs/{{ certificates_server }}.crt"
    foreman_proxy_client_key: "{{ certificates_ca_directory }}/private/{{ certificates_server }}-client.key"
    foreman_proxy_client_certificate: "{{ certificates_ca_directory }}/certs/{{ certificates_server }}-client.crt"
    foreman_ca_certificate: "{{ certificates_ca_directory }}/certs/ca.crt"
    foreman_client_key: "{{ certificates_ca_directory }}/private/{{ certificates_server }}-client.key"
    foreman_client_certificate: "{{ certificates_ca_directory }}/certs/{{ certificates_server }}-client.crt"
    foreman_db_password: "CHANGEME"
    httpd_server_ca_certificate: "{{ certificates_ca_directory }}/certs/ca.crt"
    httpd_client_ca_certificate: "{{ certificates_ca_directory }}/certs/ca.crt"
    httpd_server_certificate: "{{ certificates_ca_directory }}/certs/{{ certificates_server }}.crt"
    httpd_server_key: "{{ certificates_ca_directory }}/private/{{ certificates_server }}.key"
    pulp_db_password: "CHANGEME"
    postgresql_databases:
      - name: candlepin
        owner: candlepin
      - name: foreman
        owner: foreman
      - name: pulp
        owner: pulp
    postgresql_users:
      - name: candlepin
        password: "{{ candlepin_db_password }}"
      - name: foreman
        password: "{{ foreman_db_password }}"
      - name: pulp
        password: "{{ pulp_db_password }}"
    postgresql_hba_entries:
      - { type: local, database: all, user: postgres, auth_method: ident }
      - { type: local, database: all, user: all, auth_method: ident }
      - { type: host, database: all, user: postgres, address: '127.0.0.1/32', auth_method: md5 }
      - { type: host, database: all, user: postgres, address: '0.0.0.0/0', auth_method: reject }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
      - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
  roles:
    - certificates
    - geerlingguy.postgresql
    - redis
    - candlepin
    - httpd
    - pulp
    - foreman_proxy
    - foreman
